version: "3"
services:
  app:
    image: "node:14.16.1"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8123:8123"
    command: "npm start"